### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by marineLZ** [xuechunxu/DiTing#12]
Dear authors，
I have 90 samples（about 6Gbp/ sample）. When running to 7/12 step， errors occur. 

Could you please kindly help us to solve it?

**Errors are as follows:**

[7/12] KEGG annotation by hmmsearch
Traceback (most recent call last):
  File "/home/zhoulei/miniconda2/envs/diting0.9/bin/diting.py", line 259, in <module>
    main()
  File "/home/zhoulei/miniconda2/envs/diting0.9/bin/diting.py", line 184, in main
    kegg_annotation(faa, bn, kegg_pieces_dir, KODB_DIR, ko_dic, THREADS)
  File "/home/zhoulei/miniconda2/envs/diting0.9/bin/scripts/func.py", line 150, in kegg_annotation
    process = Pool(threads)
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/zhoulei/miniconda2/envs/diting0.9/lib/python3.7/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

real    3863m47.974s
user    162981m39.911s
sys     4501m43.851s

**Comment by SilentGene** [comment]
hi @marineLZ , sorry I haven't had that problem on my end. It seems like a system problem. Can I know what system (Linux / OS) were you running the program on? Also, can you attach the command line that you used for us to investigate the issue?

**Comment by xuechunxu** [comment]
您好，

可能的原因是样本数太多，导致KEGG注释的时候作业数目太多。您可以把90个样本分为3组运行，最后再合并结果，因为DiTing计算的时候，每个样本是分开运行的，最终结果可以很容易地合并的。

祝好
春旭

**Comment by marineLZ** [comment]
嗯嗯，我就是这么操作的，分开了几组来跑。谢谢。

**Comment by SilentGene** [comment]
Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.
