### ISSUE TITLE
When input .fastq.gz files ,it gets wrong

### ISSUE THREAD

**Issue by ArthurKaslen** [xuechunxu/DiTing#17]
-----Here is the wrong code-----
2022-08-19 23:41:23 [INFO    ] User input: /home/miniconda3/envs/diting-env/bin/diting.py -r rawdata -o testone -n 120
 **************[1/12] Check database***************
2022-08-19 23:41:23 [INFO    ] The KEGG database is set
2022-08-19 23:41:23 [INFO    ] The DMSP database is set
2022-08-19 23:41:23 [INFO    ] ***********[2/12] Metagenomic assembly************
2022-08-19 23:41:23 [INFO    ] Megahit Assembly for GZ36_GJ_1.raw
2022-08-19 23:41:23 [INFO    ] Metagenomic assembly by MEGAHIT started
2022-08-19 23:41:23 [INFO    ] megahit -1 rawdata/GZ36_GJ_1.raw_1.fastq.gz -2 rawdata/GZ36_GJ_1.raw_2.fastq.gz -o testone/assembly_tmp -t 120
2022-08-19 23:41:23 - MEGAHIT v1.2.9
2022-08-19 23:41:23 - Using megahit_core with POPCNT support
2022-08-19 23:41:23 - Convert reads to binary library
gzip: /home/rawdata/GZ36_GJ_1.raw_1.fastq.gz: invalid compressed data--crc error

gzip: /home/rawdata/GZ36_GJ_1.raw_1.fastq.gz: invalid compressed data--length error
2022-08-19 23:43:07 - b'INFO  sequence/io/sequence_lib.cpp  :   75 - Lib 0 (/home/yanghekun/rawdata/GZ36_GJ_1.raw_1.fastq.gz,/home/rawdata/GZ36_GJ_1.raw_2.fastq.gz): pe, 46229166 reads, 150 max length'
2022-08-19 23:43:07 - b'INFO  utils/utils.h                 :  152 - Real: 103.7972\tuser: 72.1272\tsys: 10.2173\tmaxrss: 248000'
2022-08-19 23:43:07 - Error occurs when reading inputs
Traceback (most recent call last):
  File "/home/miniconda3/envs/diting-env/bin/diting.py", line 259, in <module>
    main()
  File "/home/miniconda3/envs/diting-env/bin/diting.py", line 109, in main
    copy(assembly_ori, assembly_tar)
  File "/home/miniconda3/envs/diting-env/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/miniconda3/envs/diting-env/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'testone/assembly_tmp/final.contigs.fa'

**Comment by ArthurKaslen** [comment]
Could you tell me how to solve the problem?
Thanks a lot

**Comment by SilentGene** [comment]
hi @ArthurKaslen , 

It looks like the program had a problem when trying to unzip your fastq.gz file. Could you check the data integrity of the .gz files? A typical scenario is that people have incomplete or corrupted reads files during data transmission. Or you could try unzipping your fastq.gz file manually first and then run the program.

Regards,
Heyu

**Comment by ArthurKaslen** [comment]
hi @SilentGene ,
I re-uploaded my data, it seems to be running successfully. However, it stops at "Build graph for k = 21" for a long time.
-----Here is my code-----
2022-08-20 19:12:16 - k-max reset to: 141 
2022-08-20 19:12:16 - Start assembly. Number of CPU threads 100 
2022-08-20 19:12:16 - k list: 21,29,39,59,79,99,119,141 
2022-08-20 19:12:16 - Memory used: 1947493804032
2022-08-20 19:12:16 - Extract solid (k+1)-mers for k = 21 
2022-08-20 19:13:25 - Build graph for k = 21 

Do i have too much data(up to 5GB .gz file) or anything else gets wrong?
thanks a lot
Arthur

**Comment by ArthurKaslen** [comment]
okay，thanks
