### ISSUE TITLE
Error for visualize the abundance table using my own combination of samples

### ISSUE THREAD

**Issue by laibinhuang** [xuechunxu/DiTing#23]
Dear Xue,

thank you for your program here, I would like to discuss a recent issue I have met:

I group my samples in  **pathways_relative_abundance.tab,** but it produces the error when I use:

"/home/lbhuang/miniconda3/envs/diting-env/bin/diting.py" -vis "/home/lbhuang/Moore/Diting/results/pathways_relative_abundance-C.tab"

if there anyway, I can change the editing code that can use a mapping file to do this?

Thank you very much

INFO:root:Visualize abundance table
Traceback (most recent call last):
  File "/home/lbhuang/miniconda3/envs/diting-env/bin/diting.py", line 259, in <module>
    main()
  File "/home/lbhuang/miniconda3/envs/diting-env/bin/diting.py", line 13, in main
    sketch(ABUNDANCE_TABLE)
  File "/home/lbhuang/miniconda3/envs/diting-env/bin/scripts/sketch.py", line 22, in sketch
    os.mkdir('Figure_tmp')
FileExistsError: [Errno 17] File exists: 'Figure_tmp'

**Comment by microfafa-gh** [comment]
I was encountering the same issue, I don’t know if there’s a better fix but before running the code I ran these two lines: rm-rf Figure_tmp and rm -rf heatmap_tmp
Basically manually deleting the previously existing temporary folders. Hope it helps!
