### ISSUE TITLE
Error at step 8

### ISSUE THREAD

**Issue by ramalok** [xuechunxu/DiTing#24]
Hi, I’ve been running DiTing with 174 marine metagenomes, which took ca. 4 months. Then after the KEGG annotation was done, the program failed (shown below). I am wondering whether I could restart the program in step 8/12. Would that be possible?
I didn't see a "--continue" option.

thanks!

2022-12-02 05:27:36 [INFO ] KEGG annotation for SO100802
2022-12-02 17:35:53 [INFO ] KEGG annotation for BL110208
2022-12-03 12:13:16 [INFO ] KEGG annotation for SO131212
2022-12-03 13:52:27 [INFO ] **********[8/12] Merge KEGG annotations***********
2022-12-03 13:52:27 [INFO ] Merge KEGG annotations
Traceback (most recent call last):
 File "/home/apps/diting/0.9/DiTing/diting.py", line 259, in <module>
 main()
 File "/home/apps/diting/0.9/DiTing/diting.py", line 191, in main
 merge_ko(kegg_pieces_dir, ko_merged_tab)
 File "/home/apps/diting/0.9/DiTing/scripts/func.py", line 175, in merge_ko
 fo.write(basename + '\t' + gene_id + '\t' + k_number + '\n')
OSError: [Errno 5] Input/output error

**Comment by SilentGene** [comment]
Hi, 

Unfortunately, Diting doesn't support running from the stopped point now. We are considering supporting this in future releases.

Cheers,
Heyu

**Comment by SilentGene** [comment]
Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.
