### ISSUE TITLE
Atrtribute Error in check.py

### ISSUE THREAD

**Issue by tpellegrinetti** [xuechunxu/DiTing#26]
Dear Support Team,

I am writing to report an error that I am encountering while using the program. Despite testing with the example folder sample files, the error persists. I followed the installation steps described on the program's GitHub page.

Here is the traceback error message:

Traceback (most recent call last):
File "/home/thierry_bioinfo/anaconda3/envs/diting-env/bin/diting.py", line 259, in <module>
main()
File "/home/thierry_bioinfo/anaconda3/envs/diting-env/bin/diting.py", line 66, in main
BASENAMES, READS_SUF, READS_INTER = check_reads(READS_DIR)
File "/home/thierry_bioinfo/anaconda3/envs/diting-env/bin/scripts/check.py", line 66, in check_reads
reads_suf = ''.join(match_res.groups('')[1:])
AttributeError: 'NoneType' object has no attribute 'groups'

I would appreciate any assistance you can provide in resolving this error.

Thank you

**Comment by SilentGene** [comment]
Hi Thierry,

Please attach the command line that you used for this run, so we can help you solve the problem. It seems that a wrong input folder was specified.

Cheers,
Heyu

**Comment by SilentGene** [comment]
Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.
