### ISSUE TITLE
 why is " AttributeError: 'NoneType' object has no attribute 'groups'"

### ISSUE THREAD

**Issue by BruceDeng2024** [xuechunxu/DiTing#35]
when i prepare 6 sample to run diting, it occured " AttributeError: 'NoneType' object has no attribute 'groups'"
Should i add group imformation? where should i add
As follow:

(diting-env) dengzy@xy-labWS3:/home/disk3-8T/dengzy/data/WZY/wzy-yj$ /usr/local/miniconda3/envs/diting-env/bin/diting.py -r /home/disk3-8T/dengzy/data/WZY/wzy-yj/YJ-CID -o /home/disk3-8T/dengzy/data/WZY/wzy-yj/YJ_24.3.14 -n 50
2024-03-14 21:20:14 [INFO    ] **************[1/12] Check database***************
2024-03-14 21:20:14 [INFO    ] The KEGG database is set
2024-03-14 21:20:14 [INFO    ] The DMSP database is set
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/diting-env/bin/diting.py", line 255, in <module>
    main()
  File "/usr/local/miniconda3/envs/diting-env/bin/diting.py", line 62, in main
    BASENAMES, READS_SUF, READS_INTER = check_reads(READS_DIR)
  File "/usr/local/miniconda3/envs/diting-env/bin/scripts/check.py", line 66, in check_reads
    reads_suf = ''.join(match_res.groups('')[1:])
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by BruceDeng2024** [comment]
![image](https://github.com/xuechunxu/DiTing/assets/112073685/1852194c-c173-46d4-b420-c68f1e1e36b7)
