### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by pl19940314** [xuechunxu/DiTing#37]
User input: /home/meta/mdisk/pl/earthworm/fastq/VFDB_database/kofam_database/DiTing-master/diting.py -r /home/meta/mdisk/pl/soil/test_diting -o /home/meta/mdisk/pl/soil/test_diting/out -n 30 -a /home/meta/mdisk/pl/soil/test_diting/fasta
2024-07-16 14:52:32 [INFO    ] **************[1/12] Check database***************
2024-07-16 14:52:32 [INFO    ] The KEGG database is set
2024-07-16 14:52:32 [INFO    ] The DMSP database is set
Traceback (most recent call last):
  File "/home/meta/mdisk/pl/earthworm/fastq/VFDB_database/kofam_database/DiTing-master/diting.py", line 259, in <module>
    main()
  File "/home/meta/mdisk/pl/earthworm/fastq/VFDB_database/kofam_database/DiTing-master/diting.py", line 66, in main
    BASENAMES, READS_SUF, READS_INTER = check_reads(READS_DIR)
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meta/mdisk/pl/earthworm/fastq/VFDB_database/kofam_database/DiTing-master/scripts/check.py", line 66, in check_reads
    reads_suf = ''.join(match_res.groups('')[1:])
                        ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by pl19940314** [comment]
i had met this problem, i had combined _1.fq.gz and _2.fq.gz , but it met this problem.

**Comment by lexikazen** [comment]
Has anyone solved this problem? I'm having this issue as well

**Comment by SilentGene** [comment]
Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.

**Comment by XiaomengWang0413** [comment]
> Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.

Hello, when I run the V2 version, the aforementioned problem still occurred. AttributeError in file "/data/home/xiaomeng/miniconda3/envs/diting/lib/python3.13/site-packages/diting/workflow/Snakefile", line 29:
'NoneType' object has no attribute 'groups'
  File "/data/home/xiaomeng/miniconda3/envs/diting/lib/python3.13/site-packages/diting/workflow/Snakefile", line 29, in <module>
  File "/data/home/xiaomeng/miniconda3/envs/diting/lib/python3.13/site-packages/diting/workflow/scripts/check.py", line 68, in check_reads

**Comment by SilentGene** [comment]
@XiaomengWang0413 This is most likely happening because the read file names in your input reads folder don’t match up as pairs. Could you share a few examples of your read file names?

**Comment by SilentGene** [comment]
I’ve added a more specific error-checking function in the first-step data validation, so it should now point out this issue more clearly. Appreciate the feedback!
