### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by bigsuicideparty** [xuechunxu/DiTing#5]
Dear Sir or Madam,

I followed your installation recommondations but I am unable to run DiTing on the example read data. 

with:

diting.py -r /ext/DiTing/example -o Clean-reads_interleaved.diting.out

I get the following error message:

Traceback (most recent call last):
  File "/ext/DiTing/diting.py", line 255, in <module>
    main()
  File "/ext/DiTing/diting.py", line 62, in main
    BASENAMES, READS_SUF, READS_INTER = check_reads(READS_DIR)
  File "/ext/DiTing/scripts/check.py", line 66, in check_reads
    reads_suf = ''.join(match_res.groups('')[1:])
AttributeError: 'NoneType' object has no attribute 'groups'

Could you help me solve this problem?

Kind regards

**Comment by xuechunxu** [comment]
Hi,

Could you please show the contents of your directory '/ext/DiTing/example'?

Best
Chunxu

**Comment by bigsuicideparty** [comment]
Hey,

it is:

Sample1.fq  sample2.fq  sample3.fq

Best

**Comment by xuechunxu** [comment]
Hey,

In my opinion, the `/ext/DiTing/example` is a `absolute path`. Are you sure the example data are in there? 

You can enter the previous directory of the  `example` directory, and run `diting.py -r example -o Clean-reads_interleaved.diting.out`. 

Best

**Comment by bigsuicideparty** [comment]
Running the from the folder /ext/DiTing both

diting.py -r /ext/DiTing/example -o Clean-reads_interleaved.diting.out

and

diting.py -r example -o Clean-reads_interleaved.diting.out

will give me the same error message:

2021-09-15 08:42:52 [INFO    ] **************[1/12] Check database***************
2021-09-15 08:42:52 [INFO    ] The KEGG database is set
2021-09-15 08:42:52 [INFO    ] The DMSP database is set
Traceback (most recent call last):
  File "/ext/anaconda3/envs/diting-env/bin/diting.py", line 255, in <module>
    main()
  File "/ext/anaconda3/envs/diting-env/bin/diting.py", line 62, in main
    BASENAMES, READS_SUF, READS_INTER = check_reads(READS_DIR)
  File "/ext/anaconda3/envs/diting-env/bin/scripts/check.py", line 66, in check_reads
    reads_suf = ''.join(match_res.groups('')[1:])
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by bigsuicideparty** [comment]
The output of ls example is

Sample1.fq  sample2.fq  sample3.fq

**Comment by xuechunxu** [comment]
Hey,

I have run it like you. It has no problem.
Here is `example` folder:
![image](https://user-images.githubusercontent.com/23622076/133425285-dab0473d-d7c7-4818-8c64-1459d530e1d2.png)

Enter the previous directory of the `example` directory, and run `diting.py -r example -o Clean-reads_interleaved.diting.out`:
![image](https://user-images.githubusercontent.com/23622076/133425540-2100c734-db2a-404c-83d3-0945ca624810.png)

It works well.

Could please show your screenshots?

Best

**Comment by bigsuicideparty** [comment]
Alright, I figured it out. I created an additional folder inside the example folder before the run which did conflict with your script. Now I am able to run the script like you, except that it crashes at step 7/12:

![Screen Shot 2021-09-15 at 14 13 42](https://user-images.githubusercontent.com/60916232/133431699-dbcd9433-94d3-48d5-8c7d-b0dc466caf8c.png)

**Comment by xuechunxu** [comment]
Hey,

It had a bug in `script/func.py`. I have revised it. You can download the file `script/func.py` and replace that in the folder `~/miniconda2/envs/diting-env/bin/scripts` in your conda environment.
I will update the DiTing through conda later. Thus you can reinstall DiTing after my update.

Best

**Comment by bigsuicideparty** [comment]
Thank you for your fast help. I managed to get it to run with the sample files, however when trying to run diting with my own assembly and read files I get an error at step [9/12]:

![Screen Shot 2021-09-16 at 09 51 57](https://user-images.githubusercontent.com/60916232/133572655-cb4c02cb-afa3-47b5-943e-7eee6b164fa5.png)

**Comment by SilentGene** [comment]
Hi @bigsuicideparty , 

Sorry for the inconvenience. Could you please attach the full `log.txt` file generated from this failure? That would help us investigate where the problem is.

Thanks,
Heyu

**Comment by bigsuicideparty** [comment]
log.txt is attached
Please ignore the early timestamps as I had to restart the pipeline due to naming issues

[log.txt](https://github.com/xuechunxu/DiTing/files/7177953/log.txt)

**Comment by SilentGene** [comment]
Hi all, you’re very welcome to try the new version [DiTing v2](https://github.com/SilentGene/DiTing), where the problem you mentioned should no longer occur.
